### ISSUE TITLE
Missing command line tool !

### ISSUE THREAD

**Issue by abourget** [coddingtonbear/go-jsonselect#7]
This would be reallly cool to have a CLI tool use this and filter input files.

**Comment by coddingtonbear** [comment]
It sounds like [jsonselector](https://github.com/coddingtonbear/jsonselector) is what you're talking about, but if there's something else you're hoping for -- feel free to add it as a feature and post a pull request.

**Comment by abourget** [comment]
oh ! shoot.. just coded one! will take a look !
