### ISSUE TITLE
API refactor

### ISSUE THREAD

**Issue by abourget** [coddingtonbear/go-jsonselect#8]
Couldn't we have the selector be analyzed once, and then used to parse some bodies ? Instead of creating the parser from a body ?

I want to parse thousands of JSON documents, I don,t want to reparse de selector for each line! Doesn't that make sense ? 

Just like the RegExp package works, you compile the pattern, then apply it once or many times!

**Comment by coddingtonbear** [comment]
Sounds like a good idea, @abourget! Pull requests welcome.
